---
services:
  nginx:
    container_name: nginx-demo
    image: nginx:latest
    env_file:
      - .env
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-https.tls=true
      - traefik.http.routers.nginx-https.tls.certresolver=cloudflare
      - traefik.http.routers.nginx-https.entrypoints=websecure
      - traefik.http.routers.nginx-https.rule=Host(`${HOSTNAME}`)
    restart: unless-stopped
networks:
  frontend:
    external: true